# Generated by Django 4.1.2 on 2022-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('number_of_pages', models.CharField(blank=True, max_length=10, null=True)),
                ('publishers', models.JSONField(blank=True, null=True)),
                ('publish_places', models.JSONField(blank=True, null=True)),
                ('publish_date', models.CharField(blank=True, max_length=20, null=True)),
                ('subjects', models.JSONField(blank=True, null=True)),
                ('subject_places', models.JSONField(blank=True, null=True)),
                ('subject_people', models.JSONField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
